galley:
  host: galley
  port: 8085

cassandra:
  endpoint:
    host: cassandra
    port: 9042
  keyspace: galley_test

brig:
  host: brig
  port: 8082

gundeck:
  host: gundeck
  port: 8086

spar:
  host: spar
  port: 8088

settings:
  httpPoolSize: 1024
  maxTeamSize: 128
  maxConvSize: 128
  intraListing: false
  conversationCodeURI: https://cannon/join/
  defaultTeamTokenSettings:
    # 28 days
    user_token_timeout_seconds: 2419200
    # 1 day
    session_token_timeout_seconds: 86400
    # 15 minutes
    access_token_timeout_seconds: 900
    # 7 days
    provider_token_timeout_seconds: 604800

logLevel: Info
logNetStrings: false
