networks:
  docker-ephemeral_tools_demo_wire:
    external: false

version: '2'
services:
  stern:
    image: quay.io/wire/stern
    ports:
      - 127.0.0.1:8091:8091
    volumes:
      - ./:/configs
    entrypoint:
      - /usr/bin/stern
      - -c
      - /configs/conf/stern.demo-docker.yaml
    working_dir: /configs
    networks:
      - docker-ephemeral_tools_demo_wire

  nginx:
    image: nginx:1.15.12-alpine
    depends_on:
      - stern
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./:/configs
    entrypoint:
      - /usr/sbin/nginx
      - -p
      - /configs
      - -c
      - /configs/conf/nginx/nginx-docker.conf
    working_dir: /configs
    networks:
      - docker-ephemeral_tools_demo_wire
