flags:
  time-locale-compat:
    old-locale: false
packages:
- '.'
extra-deps:
- StateVar-1.1.0.4
- aeson-1.0.2.0
- aeson-pretty-0.8.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- appar-0.1.4
- async-2.1.0
- atomic-primops-0.8.0.4
- attoparsec-0.13.1.0
- auto-update-0.1.4
- base-compat-0.9.1
- base-orphans-0.5.4
- bifunctors-5.4.1
- blaze-builder-0.4.0.2
- byteorder-1.0.4
- bytestring-builder-0.10.8.1.0
- case-insensitive-1.2.0.7
- clock-0.7.2
- cmdargs-0.10.14
- comonad-5
- contravariant-1.4
- distributive-0.5.0.2
- dlist-0.8.0.2
- double-conversion-2.0.1.0
- easy-file-0.2.1
- exceptions-0.8.3
- fast-logger-2.4.7
- hashable-1.2.4.0
- hex-0.1.2
- http-date-0.0.6.1
- http-types-0.9.1
- http2-1.6.2
- iproute-1.7.0
- mtl-2.2.1
- network-2.6.3.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.13.0.0
- primitive-0.6.1.0
- prometheus-0.4.0
- psqueues-0.2.2.2
- random-1.1
- scientific-0.3.4.9
- semigroups-0.18.2
- simple-sendfile-0.2.25
- stm-2.4.4.1
- streaming-commons-0.1.16
- tagged-0.8.5
- text-1.2.2.1
- time-locale-compat-0.1.1.3
- tinylog-0.14.0
- transformers-compat-0.5.1.4
- unix-compat-0.4.2.0
- unix-time-0.3.7
- unordered-containers-0.2.7.1
- vault-0.3.0.6
- vector-0.11.0.0
- void-0.7.1
- wai-3.2.1.1
- warp-3.2.8
- word8-0.1.2
- zlib-0.6.1.1
resolver: ghc-8.0.1
